---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by nyovape1.
--- DateTime: 5/25/2019 8:12 PM
---

waypoints = setmetatable({}, {
	__index = function(tbl, key)
		local result = rawget(tbl, key)
		print(string.format('%s, %s', key, result))
		if not result and type(key) == "number" then
			result = rawget(tbl, math.min(math.max(1, key), #tbl))
			print(string.format( 'xxx %s, %s', math.min(math.max(1, key), #tbl), result))
		end
		return result
	end
})

table.insert(waypoints, {x=1})
table.insert(waypoints, {x=2})

print(waypoints[1].x)
print(waypoints[2].x)
print(waypoints[3].x)
print(waypoints[-3].x)
print(waypoints['kakk'])